default_language_version:
  python: python3.7

repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.8.0
    hooks:
    - id: seed-isort-config
      args: [--exclude=.*/__init__.py]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.17
    hooks:
    -   id: isort
        exclude: .*/__init__.py
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    - id: autopep8
      exclude: .*/__init__.py
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0  # Use the ref you want to point at
    hooks:
      - id: flake8
        exclude: .*/__init__.py
      - id: check-merge-conflict
