default_language_version:
  python: python3.7

repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.8.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.17
    hooks:
      - id: isort
        exclude: .*/__init__.py
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: flake8
        exclude: .*/__init__.py
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.3.0
    hooks:
      - id: python-no-log-warn
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
      - id: mypy
